---
- name: Make sure dyndns user exists
  user:
    name: dyndns
    state: present
  delegate_to: "{{ dyndns_host }}"

- name: add user's authorized_keys
  authorized_key:
    user: dyndns
    manage_dir: True
    key: "{{ dyndns_pubkey }}"
    state: present
    exclusive: no
  delegate_to: "{{ dyndns_host }}"

- name: The DynDNS-cronjob exists
  cron:
    user: root
    name: "DynDNS"
    minute: "*"
    hour: "*"
    job: 'echo "$(curl -4 --fail -s -S http://ipv4.xnet.space) {{ dyndns_zone }}" > /root/hosts && scp /root/hosts dyndns@{{ dyndns_host }}:hosts'
