---
yate_cleanup_config: true

yate_config:
  accfile:
    dtag_privat:
      enabled: 'yes'
      protocol: sip
      description: telekom4
      interval: 600
      username: "0049551484725"
      authname: "{{ lookup('passwordstore', 't-online.de') }}"
      password: "{{ lookup('passwordstore', 't-online.de subkey=email') }}"
      registrar: tel.t-online.de:5060
      domain: tel.t-online.de
      localaddress: 'yes'
      #outbound: tel.t-online.de:5060
      #ip_transport: tcp
    epvpn:
      enabled: 'yes'
      protocol: sip
      description: eventphone_epvpn
      interval: 600
      registrar: hg.eventphone.de:5060
      localaddress: 'yes'
      username: "{{ lookup('passwordstore', 'infra/eventphone.de/epvpn_home subkey=user') }}"
      password: "{{ lookup('passwordstore', 'infra/eventphone.de/epvpn_home') }}"
  regfile:
    'l01':
      password: "{{ lookup('passwordstore', 'infra/yate-test.int.goe.de.n0emis.eu/phones') }}"
    'l02':
      password: "{{ lookup('passwordstore', 'infra/yate-test.int.goe.de.n0emis.eu/phones') }}"
    'l03':
      password: "{{ lookup('passwordstore', 'infra/yate-test.int.goe.de.n0emis.eu/phones') }}"
    'l04':
      password: "{{ lookup('passwordstore', 'infra/yate-test.int.goe.de.n0emis.eu/phones') }}"
    'l05':
      password: "{{ lookup('passwordstore', 'infra/yate-test.int.goe.de.n0emis.eu/phones') }}"
    'l06':
      password: "{{ lookup('passwordstore', 'infra/yate-test.int.goe.de.n0emis.eu/phones') }}"
    'l07':
      password: "{{ lookup('passwordstore', 'infra/yate-test.int.goe.de.n0emis.eu/phones') }}"
    'l08':
      password: "{{ lookup('passwordstore', 'infra/yate-test.int.goe.de.n0emis.eu/phones') }}"
    'l09':
      password: "{{ lookup('passwordstore', 'infra/yate-test.int.goe.de.n0emis.eu/phones') }}"
    'l10':
      password: "{{ lookup('passwordstore', 'infra/yate-test.int.goe.de.n0emis.eu/phones') }}"
    'l11':
      password: "{{ lookup('passwordstore', 'infra/yate-test.int.goe.de.n0emis.eu/phones') }}"
  regexroute:
    default:
      '${username}^$': '-;error=noauth'

      "^5374$": "goto epvpn_incoming"

      '^0049551484725$': 'goto dtag_privat_incoming'
      '^\+49551484725$': 'goto dtag_privat_incoming'

      '^06$': 'return;called=l06'
      '^07$': 'return;called=l07'
      '^08$': 'return;called=l08'
      '^09$': 'return;called=l09'
      '^10$': 'return;called=l10'
      '^11$': 'return;called=l11'

      '^[0-9]\{4\}$': "goto epvpn_outgoing"

      '^00\([0-9]*\)$': 'goto dtag_privat_outgoing; caller=+\1'
      '^0\([0-9]*\)$': 'goto dtag_privat_outgoing; caller=+49\1'
      '^\([0-9]*\)$': 'goto dtag_privat_outgoing; caller=+49551\1'
      #'^\([0-9]*\)$': 'goto dtag_privat_outgoing;'

      '^99991001$': 'tone/dial'
      '^99991002$': 'tone/busy'
      '^99991003$': 'tone/ring'
      '^99991004$': 'tone/specdial'
      '^99991005$': 'tone/congestion'
      '^99991006$': 'tone/outoforder'
      '^99991007$': 'tone/milliwatt'
      '^99991008$': 'tone/info'
    dtag_privat_outgoing:
      #'^00\([0-9]*\)$': 'sip/sip:+\1;line=dtag_privat;caller=0049551484725;domain=tel.t-online.de'
      #'^0\([0-9]*\)$': 'sip/sip:+49\1;line=dtag_privat;caller=0049551484725;domain=tel.t-online.de'
      #'^\([0-9]*\)$': 'sip/sip:+49551\1;line=dtag_privat;caller=0049551484725;domain=tel.t-online.de'
      '.*$': "sip/sip:\\0;line=dtag_privat;caller=0049551484725;domain=tel.t-online.de"
    dtag_privat_incoming:
      '^.*$': 'fork lateroute/l06 lateroute/l09 lateroute/l10 lateroute/l11'
    epvpn_outgoing:
      '.*$': "sip/sip:\\0;line=epvpn;caller=5374;domain=hg.eventphone.de"
    epvpn_incoming:
      '^.*$': 'fork lateroute/l06 lateroute/l10 lateroute/l11'
  h323chan:
    ep:
      ep: 'true'
      gw: 'false'
      ident: yate
  yate:
    general:
      msgsniff: 'yes'
    localsym:
      h323chan.yate: 'yes'
    modules:
      regexroute.yate: 'true'
      accfile.yate: 'true'
      regfile.yate: 'true'
      msgsniff.yate: 'true'
