---
- name: configure openwrt accesspoints
  hosts: openwrt
  gather_facts: no
  pre_tasks:
    - name: 'install python'
      raw: 'opkg update && opkg install python3-light'

  tasks:
    - name: remove packages
      opkg:
        name: wpad-mini luci luci-app-firewall luci-mod-admin-full luci-proto-ipv6 luci-proto-ppp luci-theme-bootstrap luci-base luci-lib-jsonc luci-lib-nixio luci-lib-ip
        state: absent

    - name: install wpad
      opkg:
        name: wpad
        state: present
        update_cache: yes
