---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Create A records
    inwx.collection.dns:
      domain: "{{ item.domain }}"
      type: A
      record: "{{ item.record }}"
      value: "{{ item.value }}"
      username: "{{ inwx_user }}"
      password: "{{ inwx_password }}"
    with_items:
      - domain: n0emis.eu
        record: ganymed.het.hel.fl
        value: 95.217.163.175
      - domain: n0emis.eu
        record: bbb.het.nbg.de
        value: 116.203.19.67

  - name: Create AAAA records
    inwx.collection.dns:
      domain: "{{ item.domain }}"
      type: AAAA
      record: "{{ item.record }}"
      value: "{{ item.value }}"
      username: "{{ inwx_user }}"
      password: "{{ inwx_password }}"
    with_items:
      - domain: n0emis.eu
        record: ganymed.het.hel.fl
        value: 2a01:4f9:c010:7b6e::1
      - domain: n0emis.eu
        record: bbb.het.nbg.de
        value: 2a01:4f8:c0c:a15b::1

  - name: Create MX records
    inwx.collection.dns:
      domain: "{{ item.domain }}"
      type: MX
      record: "{{ item.record }}"
      value: 'ganymed.het.hel.fl.n0emis.eu'
      username: "{{ inwx_user }}"
      password: "{{ inwx_password }}"
    with_items:
      - domain: n0emis.eu
        record: ''
      - domain: n0emis.eu
        record: 'services'
      - domain: n0emis.de
        record: ''
      - domain: noemis.me
        record: ''
      - domain: n0emis.eu
        record: dev

  - name: Create TLSA records
    inwx.collection.dns:
      domain: n0emis.eu
      record: "{{ item }}"
      type: TLSA
      cert_usage: 3
      selector: 1
      hash_type: 1
      value: c9c26f6bbc3de806274af05fdce17eb019a6c2fb7281bf5559f5dedcc07683cb
      username: "{{ inwx_user }}"
      password: "{{ inwx_password }}"
    with_items:
      - _25._tcp.ganymed.het.hel.fl
      - _443._tcp.ganymed.het.hel.fl
      - _110._tcp.ganymed.het.hel.fl
      - _143._tcp.ganymed.het.hel.fl
      - _465._tcp.ganymed.het.hel.fl
      - _587._tcp.ganymed.het.hel.fl
      - _993._tcp.ganymed.het.hel.fl
      - _995._tcp.ganymed.het.hel.fl
      - _4190._tcp.ganymed.het.hel.fl

  - name: Create CNAME records
    inwx.collection.dns:
      domain: "{{ item.domain }}"
      type: CNAME
      record: "{{ item.record }}"
      value: "{{ item.value }}"
      username: "{{ inwx_user }}"
      password: "{{ inwx_password }}"
    with_items:
      - domain: n0emis.eu
        record: autodiscover
        value: ganymed.het.hel.fl.n0emis.eu
      - domain: n0emis.eu
        record: autoconfig
        value: ganymed.het.hel.fl.n0emis.eu
      - domain: n0emis.eu
        record: imap
        value: ganymed.het.hel.fl.n0emis.eu
      - domain: n0emis.eu
        record: smtp
        value: ganymed.het.hel.fl.n0emis.eu
      - domain: n0emis.eu
        record: mail.het.hel.fl
        value: ganymed.het.hel.fl.n0emis.eu
      - domain: n0emis.eu
        record: mail
        value: ganymed.het.hel.fl.n0emis.eu

      - domain: n0emis.eu
        record: bbb
        value: bbb.het.nbg.de.n0emis.eu

      - domain: n0emis.eu
        record: elastix.int.goe.de
        value: home.noemis.me

  - name: Create other records
    inwx.collection.dns:
      domain: "{{ item.domain }}"
      type: "{{ item.type }}"
      record: "{{ item.record }}"
      value: "{{ item.value }}"
      username: "{{ inwx_user }}"
      password: "{{ inwx_password }}"
    with_items: []
