---
- import_playbook: dns.yml
  tags: dns

- hosts: all
  roles:
    - base
    - gantsign.oh-my-zsh
    - jnv.unattended-upgrades
  tags: base

- hosts: mail
  roles:
    - docker
    - mailcow
  tags: mailcow

- hosts: bbb
  roles:
    - n0emis.bigbluebutton
  tags: bbb

- hosts: pbx
  roles:
    - elastix
  tags: pbx
